### PR TITLE
Update libssl name for Heroku-20 stack

### PR DESCRIPTION
**Pull request by cte**
Similar to https://github.com/GemHQ/money-tree/pull/28.

Found with:
```bash
$ heroku run bash
find / -name libssl*
```

For reference, here's the setup used in the Heroku-20 `Dockerfile`: https://github.com/heroku/stack-images/blob/main/heroku-20/setup.sh

### CODE REVIEW

**Comment by nahurst** [comment]
Just ran in to this also but saw that you closed the PR. How did you end up solving the problem?

**Comment by cte** [comment]
This PR works fine, but I ended up ditching the gem that uses `money-tree` as a dependency altogether since the hacks / patches were starting to add up.

**Comment by nahurst** [comment]
Thanks @cte. That makes sense. I've ended up forking for now, but I hear you about things starting to add up.

**Comment by q9f** [comment]
@nahurst would #43 fix your issue?

**Pull request closed without merging**
